config/routes.rb
Lifetuning::Application.routes.draw do

  mount Rich::Engine => '/rich', :as => 'rich'

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :attendees

  resources :paymentmodes

  resources :reservations

  get "booking/book"
  get "booking/succesfull_booking"
  post "booking/do_booking"

  get "trainer/index"
  get "trainer/show"
  match "/trainer/:id" => "trainer#show"
  get "seminar/index"
  get "seminar_showroom/show"
  match "/seminar_showroom/:id" => "seminar_showroom#show"
  get "seminar/detail"
  get "seminar/booking"
  get "seminar/agb"

  ActiveAdmin.routes(self)
  
  get "home/index"
  get "home/about"
  get "home/contact"
  get "home/impressum"
  get "home/success"

  post "home/create_contact_email_msg"

  root :to => 'home#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :city, :country, :description, :lat, :lng, :name, :plz, :street_nr, :web
  has_one :termine

  def fulltext
    return "#{street_nr}, #{city}, #{country}"
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  attr_accessible :birthday, :city, :email, :firstname, :lastname, :plz, :streetnr, :tel, :reservations_attributes
  has_many :reservations
  has_many :termines, :through => :reservations
  validates_presence_of :firstname, :lastname, :city, :plz, :streetnr, :email, :birthday

  accepts_nested_attributes_for :reservations
  def address
    "#{streetnr}
    #{plz} #{city}"
  end

  def reservation_string
    restr = ""
    reservations.each do |r|
      restr += "#{r.termine.seminar.title} - #{I18n.l r.termine.start_date, format: :month} #{r.termine.start_date.year}: #{r.price.price}"
    end
    restr
  end


  def reservation_string_long
    restr = ""
    reservations.each do |r|
      restr += "#{r.termine.seminar.title} - #{I18n.l r.termine.start_date, format: :month} #{r.termine.start_date.year}\n
       #{r.price.price} #{r.price.priceclass.name} \n
       #{r.comment}\n
       #{r.day_of_payment}\n
       ----------------------"
    end
    restr
  end

  def to_s
    "#{firstname} #{lastname}"
  end

  def self.recent(int)
    Attendee.order("created_at desc").limit(int)
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :seminars
end

app/models/impressum.rb
class Impressum < ActiveRecord::Base
  attr_accessible :text

end

app/models/infoitem.rb
class Infoitem < ActiveRecord::Base
  attr_accessible :description, :seminar_id, :short_description, :title, :menu_title, :avatar
  belongs_to :seminar
  has_attached_file :avatar, path: ":rails_root/public/infoitems/:id/:style/:filename", url: "/infoitems/:id/:style/:filename"
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :email, :name, :subject, :body


  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  # def initialize
  # end

  # def initialize(attributes = {})
  #   attributes.each do |name, value|
  #     send("#{name}=", value)
  #   end
  # end

end

app/models/paymentmode.rb
class Paymentmode < ActiveRecord::Base
  attr_accessible :name
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :picturable_id, :picturable_type, :name, :item
  belongs_to :picturable, :polymorphic => true
  has_attached_file :item


end

app/models/price.rb
class Price < ActiveRecord::Base
  attr_accessible :price, :priceclass_id, :seminar_id
  belongs_to :priceclass
  belongs_to :seminar

  def to_s
    "#{price} #{priceclass.name}"
  end
end

app/models/priceclass.rb
class Priceclass < ActiveRecord::Base
  attr_accessible :name
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :attendee_id, :comment, :day_of_payment, :paymentmode_id, :termine_id, :checked, :price_id
  belongs_to :termine
  belongs_to :attendee
  belongs_to :paymentmode
  belongs_to :price

  validates_presence_of :checked, :price_id, :termine_id

  def to_s
    "#{r.termine.seminar.title} - #{r.termine.start_date.month} #{r.termine.start_date} : #{r.price.price} #{r.price.priceclass.name}"
  end
end

app/models/seminar.rb
class Seminar < ActiveRecord::Base


  attr_accessible :abschluss, :description, :title, :subtitle, :slug, :category_id, :infoitems_attributes, :termines_attributes, :pictures_attributes, :prices_attributes, :indexpic
  has_many :infoitems
  has_many :termines
  has_many :pictures, :as => :picturable
  has_many :prices
  belongs_to :category
  has_attached_file :indexpic, path: ":rails_root/public/seminar/:id/:style/:filename", url: "/seminar/:id/:style/:filename"

  accepts_nested_attributes_for :infoitems, :termines, :pictures, :prices


  extend FriendlyId
  friendly_id :title, use: :slugged

  # def should_generate_new_friendly_id?
  #   new_record?
  # end

end

app/models/termine.rb
class Termine < ActiveRecord::Base
  attr_accessible :address_id, :amount, :end_date, :seminar_id, :start_date
  belongs_to :seminar
  belongs_to :address

  def to_s
    "#{seminar.title} - #{I18n.l start_date, format: :month} #{start_date.year}"
  end
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  attr_accessible :description, :name, :subtitle, :profile_picture, :contact_data, :contact_email, :slug
  has_attached_file :profile_picture , path: ":rails_root/public/trainer/:id/:style/:filename", url: "/trainer/:id/:style/:filename"

  extend FriendlyId
  friendly_id :name, use: :slugged

  # def should_generate_new_friendly_id?
  #   new_record?
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
  end

  def contact
    @message = Message.new
  end

  def create_contact_email_msg
    @message = Message.new(params[:message])
    
    if @message.valid?
      ContactMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Nachricht wurde erfolgreich versendet. Danke sehr. Wir melden uns.")
    else
      flash.now.alert = "Bitte alle Informationen eintragen."
      render :contact
    end
  end


  def success
  end

  def impressum
  end
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/seminar_helper.rb
module SeminarHelper
end

app/helpers/trainer_helper.rb
module TrainerHelper
end

app/views/home/_seminar_preview.html.haml
.seminar_img_preview
  - Seminar.limit(3).each do |s|
    %a{href: "/seminar_showroom/#{s.slug}"}
      .img{style: "background: transparent url('#{s.indexpic.url}') center center"}
      .clear
      %p=s.title
    .clear

app/views/home/about.html.haml
%h1 NLP Lifetuning

.top_picture
  .subtitle
    %p="Seminare und Ausbildungen auf höchstem Niveau"
  .seminar_index_pic{style: "background: transparent url('/assets/hoehe1200.jpg') center center"}

.bla_bla
  %p
    Seminare sollen Spaß machen, Wissen vermitteln, Veränderungen bringen und Ressourcen zugänglich machen.
    %br
    %br
    Durch kompetente Trainer, die ihren Beruf lieben,
    %strong="sich ständig und stetig weiterbilden"
    und daran interessiert sind, den Teilnehmern 
    %strong="einen echten Profit zu liefern, wird NLP-Lifetuning geprägt."
    %br
    %br
    Mit viel Leidenschaft arbeiten wir konsequent daran, 
    %strong="jedes Seminar für dich noch ein Stückchen besser zu machen."
    Das ist manchmal schwer. Gerade dann, wenn Seminare an Firmenstrukturen angepasst werden müssen. Hierbei hilft uns die Erfahrung, die unsere Trainer aus den verschiedensten Bereichen mit in die Konzeption einfließen lassen.
    %br
    %br
    Menschlichkeit vermisst man manchmal in Seminaren oder auch im Alltag. Für uns ist es besonders wichtig, dass 
    %strong="die Seminare mit viel Menschlichkeit und Freude an der Entwicklung und Veränderung gefüllt sind."
    Gerade die Seminare, 
    %strong="die durch ihr Ziel und ihre Zielgruppe besonders intensiv sind,"
    können nur so intensiv sein, wenn ein Raum entsteht, in welchem Teilnehmer und auch Trainer sich wohl fühlen.
    %br
    %br
    Das Leben zu tunen bedeutet 
    %strong="Stärken zu stärken" 
    und 
    %strong="Schwächen zu schwächen."
    Was erst mal gegensätzlich klingt, ist auf den zweiten Blick sehr eindeutig und klar. Eine verstimmte Gitarre klingt schließlich auch nur lauter und keineswegs besser, wenn sie an einen großen Gitarrenverstärker angeschlossen wird.
    NLP-Lifetuning gibt dir das Stimmgerät und einen großen Werkzeugkasten an die Hand und du entscheidest dabei selbst, wie du deine Gitarre umstimmen magst und
    %strong="welche Werkzeuge in deinen Werkzeugkasten sollen."
    %br
    %br
    Wir versprechen dir, dass wir alles daran setzen, deine NLP-Ausbildung oder dein Seminar so intensiv, effektiv und erfolgreich wie möglich zu machen.


=render 'seminar_preview'

app/views/home/contact.html.haml
%h1="Kontakt"
.space
.contact_form
  = form_for @message, :url => home_create_contact_email_msg_path do |form| 
    %fieldset.fields
      %table
        %tr
          %td="Ihr Name"
          %td= form.text_field :name 
        %tr
          %td="Ihre Email"
          %td= form.text_field :email
        %tr
          %td="Betreff" 
          %td= form.text_field :subject
        %tr
          %td="Nachricht"
          %td= form.text_area :body 
      

      = form.submit "Abschicken" , class: "button-dark", style: "margin-left: 450px"

.contact_items
  %table
    %tr
      %td
        =image_tag("Icons/Standort.png", class: 'icon')
      %td
        NLP Lifetuning
        %br
        Am Berg 5
        %br
        35083 Wetter
    %tr
      %td
        =image_tag("Icons/Telefon.png", class: 'icon')
      %td
        064239397614
    %tr
      %td
        =image_tag("Icons/Skype.png", class: 'icon')
      %td
        Hypnovision
    %tr
      %td
        =image_tag("Icons/Mail.png", class: 'icon')
      %td
        info@nlp-lifetuning.de

  %br
  %br
  %img{src: "http://maps.googleapis.com/maps/api/staticmap?center='Am Berg 5, 35083 Wetter'&zoom=8&size=250x250&markers='Am Berg 5, 35083 Wetter'&sensor=false"}

app/views/home/index.html.haml
.index_slogan_picture
  =image_tag('index2.jpg')
%h1
  Wir zeigen dir den Weg zum Erfolg. 

.six
  Mit einer 
  %strong
    Hypnose oder NLP-Ausbildung bei uns 
  %strong="bekommst du viel mehr wie nur eine Ausbildung in NLP oder Hypnose."
  Wir haben für dich die Ausbildungen so gestaltet, dass du optimal gefördert wirst und dein Potential voll entfalten oder wecken kannst. 
  %br
  %br
  Du wirst nach einer
  %strong
    NLP-Ausbildung
  bei uns vielleicht 
  %strong="dein Leben und deinen Beruf aus einer ganz anderen Sicht sehen"
  und möglicherweise gibt dir das die Wahlmöglichkeiten, die du schon lange gesucht hast. 
  Mit dieser 
  %strong="Flexibilität, dem neuen Wissen und den vielen Werkzeugen, "
  die du bei uns in der 
  %strong
    NLP- oder Hypnoseausbildung 
  bekommst, kannst du dein Potenial völlig entfalten und dein Leben tunen. 

.last-two
  %p
    %strong
      If you always do 
      %br
      What you always did
      %br
      You will always get
      %br
      What you always got
    %br
    Abraham Lincoln

.space

.vierhundert
  %h2="Termine"
  - Termine.limit(3).each do |t|
    .termin
      .icon
        =I18n.l t.start_date, format: :month
        %br
        =t.start_date.year
      .date
        %p
          ="#{I18n.l(t.start_date, format: :short)} - #{I18n.l t.end_date, format: :short}"
          %br
          %strong=t.seminar.title
          %br
      .clear
      .buy_termin
        = link_to "jetzt anmelden", booking_book_path(termin_id: t.id)

.vierhundert
  %h2="Unsere Philosophie"
  %a{href: home_about_path}
    =image_tag('hoehemini.jpg')
  %p
    Durch kompetente Trainer, die ihren Beruf lieben,
    %strong="sich ständig und stetig weiterbilden"
    und daran interessiert sind, den Teilnehmern 
    %strong="einen echten Profit zu liefern"
    , wird NLP-Lifetuning geprägt.
    Mit viel Leidenschaft arbeiten wir konsequent daran, 
    %strong="jedes Seminar für dich noch ein Stückchen besser zu machen."
  =link_to "mehr..", home_about_path, class: "button-green"

.vierhundert
  %h2="Unser Erfolgskonzept"
  %a{href: home_about_path}
    =image_tag('erfolgmini.jpg')
  %p
    Lerne
    %strong="deine Kommunikation effektiv zu verbessern,"
    und entdecke die vielen Möglichkeiten die NLP und Hypnose im Beruf, Coaching, Vertrieb und auch Privatleben bringen.
    %br
    Durch eine NLP-Ausbildung bei uns wirst du lernen mit den verschiedensten Situationen 
    %strong="selbstbewusst und erfolgreich umzugehen." 
  =link_to "mehr..", home_success_path, class: "button-green"

.space

%h2="Trainer"
.big-content
  - Trainer.order('updated_at DESC').limit(4).each do |trainer|
    %a{href: trainer_show_path(id: trainer.id), class: 'index_trainer_preview'}
      %img{src: trainer.profile_picture.url}
      %p
        %strong=trainer.name
        %br
        =trainer.subtitle
.index_trainer_preview_text
  %p
    Erfolgreiche Seminare benötigen kompetente Trainer die ihre Arbeit verstehen. Unsere 
    %strong="Trainer sind Spezialisten"
    auf ihrem Gebiet und bringen viel Erfahrung mit.
    Uns ist es eine 
    %strong="Herzensangelegenheit" 
    dir in deinem Seminar die Möglichkeit zu geben 
    %strong
      von Experten zu lernen.

app/views/home/success.html.haml
%h1="Unsere Erfolgsstrategie"

.top_picture
  .subtitle
    %p="Wir zeigen Dir den Weg zum Erfolg"
  .seminar_index_pic{style: "background: transparent url('/assets/erfolg1200.jpg') center center"}

.bla_bla
  %p
    Mit einer Hypnose oder NLP-Ausbildung bei uns 
    %span="bekommst du viel mehr wie"
    nur eine Ausbildung in NLP oder Hypnose. Wir haben für dich die Ausbildungen so gestaltet, dass 
    %span="du optimal gefördert wirst und dein Potential voll entfalten "
    oder wecken kannst. 
    %br
    %br
    Du wirst nach einer NLP-Ausbildung bei uns vielleicht dein Leben und deinen Beruf aus einer ganz anderen Sicht sehen und möglicherweise gibt dir das die Wahlmöglichkeiten, die du schon lange gesucht hast. 
    %span=" Mit dieser Flexibilität, dem neuen Wissen und den vielen Werkzeugen,"
    die du bei uns in der NLP- oder Hypnoseausbildung bekommst, kannst du dein Potenial völlig entfalten und dein Leben tunen.
    %br
    %br
    Lerne durch NLP
    %strong="deine Kommunikation effektiv zu verbessern"
    und entdecke die vielen Möglichkeiten, die NLP und Hypnose im Coaching, Vertrieb oder auch z.B. in pädagogischen Berufen bringt. Durch eine NLP-Ausbildung bei uns wirst du lernen mit den verschiedensten Situationen 
    %strong="im Leben selbstbewusst und erfolgreich umzugehen." 
    Du wirst jederzeit 
    %strong="erkennen, wenn andere versuchen dich zu manipulieren"
    und du bekommst Werkzeuge an die Hand, um in solchen Situationen passend zu reagieren. 
    Vor Gruppen wirst du mit Leichtigkeit erfolgreich reden und dabei überzeugend wirken.
    %br
    %br
    Die richtige Strategie zu wählen, die auch erfolgreich ist, erfordert Wahlmöglichkeiten zu haben. Innerhalb der NLP-Ausbildung bei uns lernst du viele Entscheidungsstrategien kennen und wirst selbst eigene Strategien entwickeln. 
    %br
    %br
    Und wenn du jetzt noch neugieriger bist und mehr über unsere Seminare erfahren möchtest, bist du herzlich dazu eingeladen, dich auf unserer Website zu informieren. Wenn es dir schwer fällt 
    %strong="das richtige Seminar oder die Ausbildung zu finden, die für dich am besten passt"
    oder du vielleicht noch ganz andere Fragen hast, sprich uns einfach direkt an. Wir kümmern uns gerne um deine offenen Fragen. 
    %br
    %br
    Dein NLP-Lifetuning Team 

=render 'seminar_preview'