config/routes.rb
Lifetuning::Application.routes.draw do

  mount Rich::Engine => '/rich', :as => 'rich'

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :attendees

  resources :paymentmodes

  resources :reservations

  get "booking/book"
  get "booking/succesfull_booking"
  post "booking/do_booking"

  get "trainer/index"
  get "trainer/show"
  match "/trainer/:id" => "trainer#show"
  get "seminar/index"
  get "seminar_showroom/show"
  match "/seminar_showroom/:id" => "seminar_showroom#show"
  get "seminar/detail"
  get "seminar/booking"
  get "seminar/agb"

  ActiveAdmin.routes(self)
  
  get "home/index"
  get "home/about"
  get "home/contact"
  get "home/impressum"
  get "home/success"

  post "home/create_contact_email_msg"

  root :to => 'home#index'

end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  def book
    begin
      @termin = Termine.find(params[:termin_id])
      @attendee=Attendee.new 
      @reservation= Reservation.new      
    rescue
      redirect_to seminar_index_path
    end
  end

  def do_booking    
    begin
      @attendee=Attendee.new(params[:attendee])
      @reservation=Reservation.new(params[:reservation])
      @termin = Termine.find(@reservation.termine_id)    

      @reservation.paymentmode=Paymentmode.first
      @reservation.attendee=@attendee

      

      respond_to do |format|
        if @reservation.valid? && @attendee.valid?
          if @attendee.save && @reservation.save
            format.html { redirect_to '/booking/succesfull_booking'}
            BookingNotification.confirm(@attendee, @reservation).deliver
            BookingNotification.stefan(@attendee, @reservation).deliver
          end
        else
          format.html { render action: "book" }
        end
      end
    rescue => e
      binding.pry
      #redirect_to seminar_index_path
    end
  end

  def succesfull_booking

  end
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/views/booking/book.html.haml
.booking
  %h1="Buchung"
  .attendee_formular
    %h2="Persönliche Daten"
    = form_for @attendee, url: booking_do_booking_path, validation: true do |f|
      -if @attendee.errors.any?
        / #error_explanation
        /   %h2= "#{pluralize(@attendee.errors.count, "error")} prohibited this attendee from being saved:"
        /   %ul
        /     - @attendee.errors.full_messages.each do |msg|
        /       %li= msg
      
      %table
        %tr
          %td="Vorname"
          %td= f.text_field :firstname
        %tr
          %td="Nachname"
          %td= f.text_field :lastname
 
        %tr
          %td="Geburtsdatum"
          %td= f.date_select :birthday, end_year: Time.now.year - 100, start_year: Time.now.year
        %tr
          %td="Straße und Hausnummer"
          %td=f.text_field :streetnr
        %tr
          %td="PLZ"
          %td= f.text_field :plz
        %tr
          %td="Stadt"
          %td= f.text_field :city
        %tr
          %td="Email"
          %td= f.email_field :email
        %tr
          %td="Telefon"
          %td= f.phone_field :tel

        =fields_for @reservation do |fr| 
          -if @reservation.errors.any?
            #error_explanation
              %h2= "#{pluralize(@reservation.errors.count, "error")} prohibited this reservation from being saved:"
              %ul
                - @reservation.errors.full_messages.each do |msg|
                  %li= msg
          %tr
            %td{style: "vertical-align: top"}="Kommentar (optional)"
            %td
              = fr.text_area :comment, rows: 5
              = fr.hidden_field :termine_id, value: @termin.id
          %tr
            %td="Preiskategorie"
            %td
              -@termin.seminar.prices.each do |p|                                  
                =fr.radio_button :price_id, p.id
                ="#{p.priceclass.name} - #{p.price} €"
                %br
          %tr
            %td{colspan: 2}                
              .space
                =fr.check_box :checked
                Hiermit bestätige ich dass ich 
                =link_to "die AGB", seminar_agb_path
                zur Kenntnis genommen habe, sie akzeptiere, und mich verbindlich anmelde.
        %tr
          %td
            = f.submit 'Anmelden', class: "button-dark"
          %td


  .booking_info
    %h3=@termin.seminar.title
    %table
      %tr
        %td="Beginn"
        %td=I18n.l @termin.start_date
      %tr
        %td="Ende"
        %td=I18n.l @termin.end_date
      %tr
        %td="Dauer"
        %td=(@termin.end_date-@termin.start_date).to_i.to_s + " Tage"

    
    %h3="Kosten"
    %table
      -@termin.seminar.prices.each do |p|
        %tr
          %td=p.priceclass.name
          %td=p.price.to_s + " €"

    
    %h3="Standort"
    =render 'seminar/location', termin: @termin

app/views/booking/succesfull_booking.html.haml
%h1="Willkommen"
.big-content
  %p
    Gratulation!
    %br
    %br
    So eben hast Du dich für die Teilnahme an unserem Seminar entschieden und damit die Weichen für Dich gestellt neue Fähigkeiten zu lernen. Wir freuen uns schon darauf Dich persönlich kennenzulernen und werden alles daran setzen das Seminar so zu gestalten das sie für Dich unvergesslich und erfolgreich ist.
    %br
    %br
    Du hast so eben eine Anmeldebestätigung per Mail bekommen!
    %br
    %br
    Wir freuen uns auf Dich
    %br
    Lifecoach Stefan Friedrich und das gesammte NLP-Lifetuning Team

.sidebar
  =image_tag 'hoehemini.jpg', style: "float: right"