config/routes.rb
Lifetuning::Application.routes.draw do

  mount Rich::Engine => '/rich', :as => 'rich'

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :attendees

  resources :paymentmodes

  resources :reservations

  get "booking/book"
  get "booking/succesfull_booking"
  post "booking/do_booking"

  get "trainer/index"
  get "trainer/show"
  match "/trainer/:id" => "trainer#show"
  get "seminar/index"
  get "seminar_showroom/show"
  match "/seminar_showroom/:id" => "seminar_showroom#show"
  get "seminar/detail"
  get "seminar/booking"
  get "seminar/agb"

  ActiveAdmin.routes(self)
  
  get "home/index"
  get "home/about"
  get "home/contact"
  get "home/impressum"
  get "home/success"

  post "home/create_contact_email_msg"

  root :to => 'home#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :city, :country, :description, :lat, :lng, :name, :plz, :street_nr, :web
  has_one :termine

  def fulltext
    return "#{street_nr}, #{city}, #{country}"
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  attr_accessible :birthday, :city, :email, :firstname, :lastname, :plz, :streetnr, :tel, :reservations_attributes
  has_many :reservations
  has_many :termines, :through => :reservations
  validates_presence_of :firstname, :lastname, :city, :plz, :streetnr, :email, :birthday

  accepts_nested_attributes_for :reservations
  def address
    "#{streetnr}
    #{plz} #{city}"
  end

  def reservation_string
    restr = ""
    reservations.each do |r|
      restr += "#{r.termine.seminar.title} - #{I18n.l r.termine.start_date, format: :month} #{r.termine.start_date.year}: #{r.price.price}"
    end
    restr
  end


  def reservation_string_long
    restr = ""
    reservations.each do |r|
      restr += "#{r.termine.seminar.title} - #{I18n.l r.termine.start_date, format: :month} #{r.termine.start_date.year}\n
       #{r.price.price} #{r.price.priceclass.name} \n
       #{r.comment}\n
       #{r.day_of_payment}\n
       ----------------------"
    end
    restr
  end

  def to_s
    "#{firstname} #{lastname}"
  end

  def self.recent(int)
    Attendee.order("created_at desc").limit(int)
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :seminars
end

app/models/impressum.rb
class Impressum < ActiveRecord::Base
  attr_accessible :text

end

app/models/infoitem.rb
class Infoitem < ActiveRecord::Base
  attr_accessible :description, :seminar_id, :short_description, :title, :menu_title, :avatar
  belongs_to :seminar
  has_attached_file :avatar, path: ":rails_root/public/infoitems/:id/:style/:filename", url: "/infoitems/:id/:style/:filename"
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :email, :name, :subject, :body


  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  # def initialize
  # end

  # def initialize(attributes = {})
  #   attributes.each do |name, value|
  #     send("#{name}=", value)
  #   end
  # end

end

app/models/paymentmode.rb
class Paymentmode < ActiveRecord::Base
  attr_accessible :name
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :picturable_id, :picturable_type, :name, :item
  belongs_to :picturable, :polymorphic => true
  has_attached_file :item


end

app/models/price.rb
class Price < ActiveRecord::Base
  attr_accessible :price, :priceclass_id, :seminar_id
  belongs_to :priceclass
  belongs_to :seminar

  def to_s
    "#{price} #{priceclass.name}"
  end
end

app/models/priceclass.rb
class Priceclass < ActiveRecord::Base
  attr_accessible :name
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :attendee_id, :comment, :day_of_payment, :paymentmode_id, :termine_id, :checked, :price_id
  belongs_to :termine
  belongs_to :attendee
  belongs_to :paymentmode
  belongs_to :price

  validates_presence_of :checked, :price_id, :termine_id

  def to_s
    "#{r.termine.seminar.title} - #{r.termine.start_date.month} #{r.termine.start_date} : #{r.price.price} #{r.price.priceclass.name}"
  end
end

app/models/seminar.rb
class Seminar < ActiveRecord::Base


  attr_accessible :abschluss, :description, :title, :subtitle, :slug, :category_id, :infoitems_attributes, :termines_attributes, :pictures_attributes, :prices_attributes, :indexpic
  has_many :infoitems
  has_many :termines
  has_many :pictures, :as => :picturable
  has_many :prices
  belongs_to :category
  has_attached_file :indexpic, path: ":rails_root/public/seminar/:id/:style/:filename", url: "/seminar/:id/:style/:filename"

  accepts_nested_attributes_for :infoitems, :termines, :pictures, :prices


  extend FriendlyId
  friendly_id :title, use: :slugged

  # def should_generate_new_friendly_id?
  #   new_record?
  # end

end

app/models/termine.rb
class Termine < ActiveRecord::Base
  attr_accessible :address_id, :amount, :end_date, :seminar_id, :start_date
  belongs_to :seminar
  belongs_to :address

  def to_s
    "#{seminar.title} - #{I18n.l start_date, format: :month} #{start_date.year}"
  end
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  attr_accessible :description, :name, :subtitle, :profile_picture, :contact_data, :contact_email, :slug
  has_attached_file :profile_picture , path: ":rails_root/public/trainer/:id/:style/:filename", url: "/trainer/:id/:style/:filename"

  extend FriendlyId
  friendly_id :name, use: :slugged

  # def should_generate_new_friendly_id?
  #   new_record?
  # end
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/seminar_helper.rb
module SeminarHelper
end

app/helpers/trainer_helper.rb
module TrainerHelper
end

app/views/booking_notification/confirm.text.erb
Hallo <%= @attendee.firstname %>,

Gratulation!

So eben hast Du dich für die Teilnahme an unserem Seminar <%= @reservation.termine.seminar.title %> vom <%= I18n.l @reservation.termine.start_date %> bis zum  <%= I18n.l @reservation.termine.end_date %> entschieden und damit die Weichen für Dich gestellt neue Fähigkeiten zu lernen. Wir freuen uns schon darauf Dich persönlich kennenzulernen und werden alles daran setzen das Seminar so zu gestalten das sie für Dich unvergesslich und erfolgreich ist.

In den nächsten Tagen erhälst du weitere Angaben, Informationen und deine Rechnung per EMail.

Wir freuen uns auf Dich
Lifecoach Stefan Friedrich und das gesammte NLP-Lifetuning Team

app/views/booking_notification/stefan.text.erb
Es gibt eine neue Anmeldung für <%= @reservation.termine.seminar.title %> im <%= I18n.l @reservation.termine.start_date, format: :month %> <%= @reservation.termine.start_date.year %>

Der neue Padawan:
  <%= @attendee.firstname %>
  <%= @attendee.lastname %>
  <%= @attendee.streetnr %>
  <%= @attendee.plz %>  <%= @attendee.city %>

Preiskategorie:
  <%= @reservation.price.price %> <%= @reservation.price.priceclass.name %>

Email:
  <%= @attendee.email %>
Telefon
  <%= @attendee.tel %>

Kümmerse dich drum wa?

app/views/layouts/_flash_message.html.haml
.clear
-if notice
  #notice
    %p=notice
-if alert
  #alert
    %p= alert

app/views/layouts/_footer.html.haml
.seminar_footer
  %h3="Seminare"
  -Category.all.each do |c|
    .footer_seminar_box
      .footer_sub_title=c.name
      %ul
        -c.seminars.each do |s|
          %li
            %a{href: seminar_showroom_show_path(id: s.id)}=s.title
      .clear
.contact_footer
  %h3
    Kontakt
  %ul.footer_contact_menu
    %li
      =link_to "Über NLP Lifetuning", home_about_path
    %li
      =link_to "Trainer", trainer_index_path
    %li
      =link_to "Kontaktformular", home_contact_path
    %li
      =link_to "AGB", seminar_agb_path
    %li
      =link_to "Impressum", home_impressum_path
.stefan_footer
  
  %table
    %tr
      %td
        =image_tag("Icons/Standort.png", class: 'icon')
      %td
        NLP Lifetuning
        %br
        Am Berg 5
        %br
        35083 Wetter
    %tr
      %td
        =image_tag("Icons/Telefon.png", class: 'icon')
      %td
        064239397614
    %tr
      %td
        =image_tag("Icons/Skype.png", class: 'icon')
      %td
        Hypnovision
    %tr
      %td
        =image_tag("Icons/Mail.png", class: 'icon')
      %td
        info@nlp-lifetuning.de

  =image_tag('nlp-logo.png')

app/views/layouts/_head.html.haml
%meta{:charset => "utf-8"}

-# Always force latest IE rendering engine (even in intranet) & Chrome Frame
%meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
%meta{:name=>"keywords", :content=>"NLP-Ausbildung,NLP-Seminar,Hypnoseausbildung,NLP,NLP-Practitioner,Seminare,Marburg,Siegen,Kassel,Frankfurt,Wiesbaden,Stefan Friedrich"}
%meta{:name=>"description", :content=>"NLP-Practioner und NLP-Masterausbildung sowie Hypnose Ausbildungen auf höchstem Niveau"}
%meta{:name=>"author", :content=>"Stefan Friedrich"}

- title ||= "NLP-Lifetuning: Seminare, NLP-Ausbildung, Hypnose Ausbildung"
%title= title

= preserve(meta_data_tags) if defined?(meta_data_tags)
= csrf_meta_tags

/= favicon_link_tag image_path('favicon.ico')


/[if lt IE 9]
  <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
= stylesheet_link_tag 'application', :media => "screen, projection"
= javascript_include_tag "application"  

= yield :head

app/views/layouts/_header.html.haml
.header
  .logo
    %a{href: "#{home_index_path}"}
      =image_tag "YYLogo.png"
  .fblike
    %iframe{src: "http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.nlp-lifetuning.de&amp;layout=button_count&amp;show_faces=true&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=80", scrolling: "no", frameborder: "0", style: "border:none; overflow:hidden; width:100%; height:80px;", allowTransparency: "true"}
  .clear
  .menu
    %ul
      %li.home_menu_item
        %a{href: "#{home_index_path}"}
          =image_tag('Home.png')
      %li.first_menu_item
        %a{href: "#{home_about_path}"}="Über NLP Lifetuning"
      %li
        %a{href: "#{seminar_index_path}"}="Seminare"
      %li
        %a{href: "#{trainer_index_path}"}="Trainer"
      %li
        %a{href: "#{home_success_path}"}="Unser Erfolgskonzept"
      %li
        %a{href: "#{home_contact_path}"}="Kontakt"
      %li
        %a{href: "#{home_impressum_path}"}="Impressum"
      %li.social_items{style: "padding: 15px 0px"}
        %a{href: 'https://www.facebook.com/NLP.Lifetuning', target: "_blank"}
          =image_tag('icon_fb.png')
        %a{href: 'https://twitter.com/NLPLifetuning', target: "_blank"}
          =image_tag('icon_twitter.png')
        %a{href: "https://www.xing.com/companies/nlp-lifetuning", target: "_blank"}
          =image_tag('icon_xing.png')


    .clear

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render partial: 'layouts/head'
  %body
    #fb-root
    :javascript
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/de_DE/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    #wrapper
      %header
        = render partial: 'layouts/header'
      .content#content
        = render partial: 'layouts/flash_message'
        = yield
      %footer.footer
        = render partial: 'layouts/footer'